### ISSUE TITLE
Is it correct behavior to use equalp for hash tables?

### ISSUE THREAD

**Issue by fisxoj** [eudoxia0/cl-yaml#14]
Hello!  Thanks for the library (and several others).

I was noticing an interesting problem recently in a project where the lowercase string "id" had special meaning as an object key and the value of a key "Id" was being passed into the special code, which made me realize that the library makes its hash tables with `:test 'equalp`, which is case-insensitive.

Just to reiterate, asking for the key `"id"` was getting me the value of the key `"Id"`, which was unexpected.

Is there a specific reason to do that, or could it be made more specific to use `'equal` instead?

**Comment by eudoxia0** [comment]
I think I got this wrong because `equalp` is the only equality testing function that works for hash tables. I'll make the change.
